### ISSUE TITLE
Dropbox sync is broken

### ISSUE THREAD

**Issue by Balur86** [Laverna/laverna#841] opened 2017-09-29 03:58 UTC
Hello,

I can sync nothing to my Dropbox. Is it something related with yesterday's Dropbox API change? Anyone notice the same or just me?

**Comment by ViSo1o** [comment] 2017-09-29 11:29
I also have this error. Can't sinc app on linux and app on the tablet

**Comment by talklittle** [comment] 2017-09-29 17:47
Developer is working on it.

Duplicate of #805

**Comment by wwebfor** [comment] 2017-09-30 10:05
I think it was fixed in 0.7.5 release.

**Closed by wwebfor** 2017-09-30 10:05 UTC
