### ISSUE TITLE
Feature Request: Cross Page Linking

### ISSUE THREAD

**Issue by CMCDragonkai** [Laverna/laverna#78] opened 2014-05-11 13:58 UTC
Would be great if Laverna supported cross page linking. Now I know it's a web app, so there are "hyperlinks", but something relative that doesn't rely on absolute links would be cool.

Maybe even a specific app related protocol like: `laverna://...etc`. Which would allow other apps to link to things on Laverna!

**Comment by claell** [comment] 2015-12-06 15:02
I guess this is an duplicate, right?

**Comment by wwebfor** [comment] 2017-12-29 11:16
I think it is a duplicate of #252. So closing.

**Closed by wwebfor** 2017-12-29 11:16 UTC
Labels: enhancement
