### ISSUE TITLE
You can export Evernote? 

### ISSUE THREAD

**Issue by tanrax** [Laverna/laverna#282] opened 2015-10-03 14:11 UTC
I mention this because if you were that button would be great!

**Comment by jcrben** [comment] 2015-10-24 05:38
Not sure I understand this issue, but it seems like a duplicate of https://github.com/Laverna/laverna/issues/45 and could probably be closed.

**Comment by claell** [comment] 2015-10-24 08:15
Maybe he wants an option to export the notes from Laverna to Evernote?

**Comment by tanrax** [comment] 2015-10-24 09:17
No, I want the opposite

**Comment by claell** [comment] 2015-10-24 12:46
Then it is a duplicate of #45 right?

**Comment by wwebfor** [comment] 2015-12-06 13:46
Close the issue since it is a duplicate.

**Closed by wwebfor** 2015-12-06 13:46 UTC
Labels: duplicate
