### ISSUE TITLE
BUG: No way to edit old notes

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#321] opened 2015-12-12 13:56 UTC
Notes created with the old Laverna can't be edited with this new version.

Tested on both smartphone and PC, with Firefox.

**Comment by romu70** [comment] 2015-12-12 14:19
This issue is linked to #322. If, for a given note, you fix the notebook (replaced the old one by a newly created one), you can edit the old notes.

**Comment by wwebfor** [comment] 2015-12-12 16:26
It is all because in the previous version we used to use numbers as IDs for notebooks. In the new version we use strings. Probably we will have to write some script which will migrate data from old DB.

**Comment by wwebfor** [comment] 2015-12-18 16:02
Closing the issue since it's a duplicate of #322

**Closed by wwebfor** 2015-12-18 16:02 UTC
Labels: bug, duplicate
